### ISSUE TITLE
Reports > DataTable2 > Download CSV for All Years

### ISSUE THREAD

**Issue by SYRCL-Kyle** [thosmos/riverdb#32]
The download CSV for All Years of WQ data is not working. Ideally this can be fixed as it is much more convenient to download all years simultaneously into one file rather than each year at a time.

Downloading one at a time can result in unnoticed errors from the tedious task of combining all of the years into a single file.

**Comment by thosmos** [comment]
This is fixed in cfb88490d3623211676ff2fcf61cb5d0c913dbe9 and uses the `data table 2` logic so columns are based on the currently selected project's params.  I added a "publish" field that should match the publish switch in the data entry form. Let me know how it looks.  

I noticed there are a bunch of therma-logger entries in 2013.  I think this was done ages ago before there was the more proper logger data type in order to get some test data into the charts when riverdb was being worked on.  I'd like to remove those and re-import them as proper thermalogger data at some point.  But for now maybe you can just filter those out.  But let me know if you see any other irregularities, of course.
